// Draw
export const GET_COORD_START = "GET_COORD_START";
export const GET_COORD_END = "GET_COORD_END";
export const SELECT_SHAPE = "SELECT_SHAPE";
export const DRAWING = "DRAWING";
export const COMPLETE_DRAWING = "COMPLETE_DRAWING";

// Canvas
export const CHANGE_CANVAS_SIZE = "CHANGE_CANVAS_SIZE";

// Edit
export const EDIT_COLOR_FILL = "EDIT_COLOR_FILL";
export const EDIT_COLOR_STROKE = "EDIT_COLOR_STROKE";
export const EDIT_COLOR_CANVAS = "EDIT_COLOR_CANVAS";
export const EDIT_OPACITY_FILL = "EDIT_OPACITY_FILL";
export const EDIT_OPACITY_STROKE = "EDIT_OPACITY_STROKE";
export const EDIT_OPACITY_CANVAS = "EDIT_OPACITY_CANVAS";
